### ISSUE TITLE
Error Creating Fidelity Bond

### ISSUE THREAD

**Issue by gianlock** [joinmarket-webui/jamdocs#26]
Hi, 
I'm trying to configure a fidelity bond, so I chose a jar, select the cj-out UTXO, review the configuration, but when I confirm I receive the following error: 
- Invalid request format. Could not load time-locked address. (in the Web UI)
- Error: not a fidelity bond wallet (in the command line)

Any suggestion? 

Thanks

**Comment by theborakompanioni** [comment]
Hey @gianlock 
> 
>     * Invalid request format. Could not load time-locked address. (in the Web UI)
> 
>     * Error: not a fidelity bond wallet (in the command line)
> 
> 
> Any suggestion?

Yes, this means your wallet does not support fidelity bonds. I suppose you have created it a while ago?
I guess it is possible to import your seedphrase in a "fidelity bond"-enabled wallet.

Take a look at https://jamdocs.org/FAQ/#can-i-import-an-existing-wallet and follow the steps.
Especially notice step 5:
> Answer questions (provide seed phrase, etc.). Make sure that you put ".jmdat" at the end of the name for the wallet, otherwise it won't be displayed in Jam. **Answer the question for support of fidelity bonds with "y" (yes).**

Hope this solves your issue. Please report back if you have any problems or further questions.

**Comment by gianlock** [comment]
Hi @theborakompanioni, 

thanks as always, that was the right solution to import my seedphrase. 

Well, actually it wasn't created too far ago, but maybe I didn't set the fidelity bond option.
