### ISSUE TITLE
Using timechain as a substitute for blockchain and emotional definition for blockchain

### ISSUE THREAD

**Issue by alexwaltz** [joinmarket-webui/jamdocs#33]
In the docs we find the term **[timechain](https://jamdocs.org/glossary/#timechain)** as a substitute for blockchain.

This is problematic for 3 reasons:
1. it's more like an inside joke, which requires users to dig through the comments of the old bitcoin code to know that Satoshi initially called it so - very few know this
2. It causes confusion - for a newcomer its just another new term he never heard, and apparently it's at the base of the blockchain
3. it is incorrect - there is good reason for satoshi to change from block to time, as he realized blockchains are not good at timekeeping. Its a glorified mistake. "I've been imitated so well I've heard people copy my mistakes." - Jimi Hendrix

The term **[blockchain](https://jamdocs.org/glossary/#blockchain)** on the other hand is described as meaningless.
While I do agree with the conclusion, I don't think this has any place in the documentation, and furthermore, it just causes more confusion.

I propose moving the definition of timechain to blockchain and removing timechain all together.

**Comment by theborakompanioni** [comment]
nack. This was not done by accident. It is explained why the terms were chosen in this way.

**Comment by alexwaltz** [comment]
It is pretty obvious this was not an accident.
Honestly don't feel this addressed any of the enumerated concerns.

I find this situation similar to how people had a problem with the words "master" & "slave".
