### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/jamdocs#4]
Add an initial "Manual installation" section - https://jamdocs.org/software/installation/#manual-installation

Should contain information about running Jam locally connecting to an already existing JM daemon.

If motivated, even start from the beginning and describe a complete installation process from scratch, ie. with installing jm, tor and starting the necessary daemons. Short description about running it with different network settings (`mainnet`, `testnet`, etc.)

**Comment by theborakompanioni** [comment]
Seems I cannot assign myself. Please assign me @dergigi.

**Comment by dergigi** [comment]
Thanks for taking care of that 🙏 - Let me know if you need any help with anything.
