### ISSUE TITLE
Add info about bitcoin-cli rescanblockchain when importing a wallet

### ISSUE THREAD

**Issue by climardo** [joinmarket-webui/jamdocs#47]
There is information in the docs about importing a wallet and the information is good, but is missing details about what to do if all balances are 0 after import. I found the info that I needed in the original joinmarket GitHub repo after seeing that wallet-tool.py is from the joinmarket project. Here: https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#creating-a-wallet

> **restart Bitcoin Core with -rescan or use bitcoin-cli rescanblockchain if you're recovering an existing wallet from backup seed Otherwise just restart this joinmarket application.**

I followed the instructions on Jam Docs and then did the following for my Start9 node:

- SSH to Start9 node
- Run `sudo docker exec -it jam.ebassy bash` to get into the jam container 
- Follow the instructions here: [Can I import an existing wallet?](https://jamdocs.org/FAQ/#can-i-import-an-existing-wallet)
- Exit the jam container with `exit`
- Get into the bitcoind container: `sudo docker exec -it bitcoind.embassy bash`
- Rescan he blockchain for the jam wallet: `bitcoin-cli -rpcwallet=embassy_jam_wallet rescanblockchain <starting-block-#> <ending-block-#.`

Sharing to save others some frustration. Thanks!

**Comment by theborakompanioni** [comment]
Hey @climardo, thanks for the heads-up.
Hopefully, these manual steps won't be necessary anymore, once https://github.com/joinmarket-webui/jam/issues/137 is implemented and released. Till then, this is a superb description for others facing the same problem and something that can be referred to :raised_hands:

**Comment by MarnixCroes** [comment]
thanks for the instructions, I'm sure it was helpful for some

closing this issue as specifying the rescan start height is part of the import process now

![image](https://github.com/user-attachments/assets/ff5661be-465d-44ad-b7ca-7bde41fe3267)

**Comment by theborakompanioni** [comment]
> thanks for the instructions, I'm sure it was helpful for some
> 
> closing this issue as specifying the rescan start height is part of the import process now

In dev mode, there is an option to rescan already imported wallets. Maybe it is time to make it available for all.. what do you think @MarnixCroes?

<img src="https://github.com/user-attachments/assets/295bf6af-c90b-4a09-b0db-6eb7162d68f8" width=350 />

**Comment by MarnixCroes** [comment]
> > thanks for the instructions, I'm sure it was helpful for some
> > closing this issue as specifying the rescan start height is part of the import process now
> 
> In dev mode, there is an option to rescan already imported wallets. Maybe it is time to make it available for all.. what do you think @MarnixCroes?
> <img alt="" width="350" src="https://private-user-images.githubusercontent.com/3358649/364312532-295bf6af-c90b-4a09-b0db-6eb7162d68f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDIwNzksIm5iZiI6MTcyNTQ0MTc3OSwicGF0aCI6Ii8zMzU4NjQ5LzM2NDMxMjUzMi0yOTViZjZhZi1jOTBiLTRhMDktYjBkYi02ZWI3MTYyZDY4ZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDkyMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg3MDIwYzE3Yzk2MGM0M2YyNTU3YWE2NWQ5MjNjMTAzOGViZGFhODBhYmM4MzYyNWU4Y2QxMjY3MmJlOWViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X9u5LYO0-7PsKu1Wdr93jcPg5RsWeB5qhlOz5em5jZ0">

sure!
would be a big UX improvement for the people who need it. as figuring out how to do a manual rescan can be a struggle for some

**Comment by theborakompanioni** [comment]
> sure! would be a big UX improvement for the people who need it. as figuring out how to do a manual rescan can be a struggle for some

https://github.com/joinmarket-webui/jam/issues/833 :pray:
