### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/jamdocs#6]
The [FAQ](https://jamdocs.org/FAQ/) is still incomplete (and also just a first version).

- [ ] Get rid of TODOs
- [ ] Add more entries, based on user feedback

**Comment by theborakompanioni** [comment]
Closing this as no more TODOs are present on the FAQ page, and entries based on user feedback can be done in separate tickets. Reopen if you think this is a mistake.
